J1939 development
Heavy-Vehicle-Networking-At-U-Tulsa/CAN-Data-Diode pull request #12
Opened 2018-09-12 18:18 UTC by hja685

# J1939-Development Pull Request #12 
Just added code for the J1939 side. This uses the Watchdog Timer to increment a counter. The request messages are pulled out of EEPROM and sent at the EEPROM defined interval. A count trigger is created based on the EEPROM specified interval. Then as the device sleeps each time it is interrupted by the WDT it will check to see if it is time to send the counter. 

I also changed sketch names to "ELD" and "J1939" to avoid confusion about which sides to do. All modifications/customizations are done in the EEPROM_MAP sketch and all values are read in from memory that may need to be tuned. 

Currently the J1939 sketch is only setup to send 2 messages at 2 intervals but the outline is there to be able to add up to 12 additional messages

the README.md file was also modified to include an EEPROM map for those interested. I also included what I am currently working on and additional discussion questions that have arose while I have been writing this. 

@bengardiner-at-irdeto : I tried to keep a practice of well-defined variables. There are quite a few of them. I hope I didn't leave any magic numbers in there. 
 
@jeremy-daily @jeremydaily : If you could review and let me know if the logic seems to progress as expected.

@Fusickb : figured it would be nice to have an extra person look at this, would you mind reading over this and see if you see any glaring errors?

Thanks guys. I really do appreciate you taking the time to review this.

2018-09-12 18:37 UTC, bengardiner-at-irdeto commented
> Currently the J1939 sketch is only setup to send 2 messages at 2 intervals but the outline is there to be able to add up to 12 additional messages

Fantastic! I'm really glad to see this feature come to life. This should enable you to use your diode in all sorts of weird places (other than the dash of trucks).
 
> @bengardiner-at-irdeto : I tried to keep a practice of well-defined variables. There are quite a few of them. I hope I didn't leave any magic numbers in there.

lol. ok -- I'll review on security implications when I see them. So far the split architecture that you fought for has paid off in so much as there were no security issues to raise...

2018-09-12 18:59 UTC, bengardiner-at-irdeto requested changes
there is much duplicated code between the two sketches. Ideally the code would be shared so a change in one place is propagated to both sketches on next rebuild. based on some googling I would say that you need to do an Arduino *Library* for this to work. But YMMV

2018-09-12 18:59 UTC, bengardiner-at-irdeto commented on examples/ELD/ELD.ino
> +  //Insert a can_val check here. We need to make sure that this is in place in the event that memory is corrupted.
Perhaps you should use an issue tracker to keep track of open items so you don't forget any and know when you're done?

2018-09-12 18:59 UTC, bengardiner-at-irdeto commented on examples/ELD/ELD.ino
> +    can_val == CAN_250KBS;
this is an equality statement, not an assignment. i.e. it will *not* assign a value to `can_val`

2018-09-12 18:59 UTC, bengardiner-at-irdeto commented on examples/ELD/ELD.ino
> +    //Didn't know how else to do a check to only do something if its not true.
you want to look at demoivre's theorem. TLDR: !(A || B || C) == !A && !B && !C

2018-09-12 18:59 UTC, bengardiner-at-irdeto commented on examples/ELD/ELD.ino
> +  if(can_Val == CAN_250KBS | can_Val == CAN_500KBS | can_Val == CAN_125KBS | can_Val == CAN_666KBS | can_Val == CAN_1000KBS){
this is a bitwise OR compound statement; you probably want logical-OR '||'

2018-09-12 18:59 UTC, bengardiner-at-irdeto commented on examples/J1939/J1939.ino
> +/* EEPROM Memory Map */
Is it the same EEPROM as the ELD side?

2018-09-12 18:59 UTC, bengardiner-at-irdeto commented on examples/J1939/J1939.ino
> +#define first_bit     0b00000001
lulz

2018-09-12 18:59 UTC, bengardiner-at-irdeto commented on examples/J1939/J1939.ino
> +byte data[8] = {0x00, 0x02, 0x04, 0x06, 0x08, 0x0A, 0x0C, 0x0F};
i think you have developed this yet (now)

2018-09-12 18:59 UTC, bengardiner-at-irdeto commented on examples/J1939/J1939.ino
> +    if(CAN0.checkReceive()== CAN_MSGAVAIL){ //Checking to see if canBus frames have come onto the bus
really weird spacing around `==`

I'm sure this sounds pedantic, but code formatting consistency makes it easier to read code and hence to spot errors in code. Use a linter

2018-09-12 18:59 UTC, bengardiner-at-irdeto commented on examples/J1939/J1939.ino
> +  /*** Setup the WDT ***/
this comment is superfluous; the function name right above it says almost-exactly the same thing.

2018-09-12 18:59 UTC, bengardiner-at-irdeto commented on examples/J1939/J1939.ino
> +  if(can_Val == CAN_250KBS | can_Val == CAN_500KBS | can_Val == CAN_125KBS | can_Val == CAN_666KBS | can_Val == CAN_1000KBS){
same comment as above - this is bitwise-OR

2018-09-12 18:59 UTC, bengardiner-at-irdeto commented on examples/J1939/J1939.ino
> +    can_val == CAN_250KBS;
same comment as above -- this is testing equality not setting anything

2018-09-12 18:59 UTC, bengardiner-at-irdeto commented on examples/J1939/J1939.ino
> +  // The following sequence is the only way we could get the clkout divisor to stay at 1
this clock setup sequence is a good candidate for extraction into a function that encapsulates 'the magic'

2018-09-12 19:26 UTC, hja685 commented on examples/ELD/ELD.ino
> +  //Insert a can_val check here. We need to make sure that this is in place in the event that memory is corrupted.
After I pushed this pull request I realized that that addition is actually obsolete. Does github have an issue tracker?

2018-09-12 19:27 UTC, hja685 commented on examples/ELD/ELD.ino
> +    can_val == CAN_250KBS;
lol I guess writing 15000 == made me just double tap it.

2018-09-12 19:27 UTC, hja685 commented on examples/ELD/ELD.ino
> +    //Didn't know how else to do a check to only do something if its not true.
I should've picked up on that one. Couldn't think of it. I'll be switching that around. Thanks ben.

2018-09-12 19:28 UTC, bengardiner-at-irdeto commented
After I pushed this pull request I realized that that addition is actually obsolete. Does github have an issue tracker?

https://www.youtube.com/watch?v=TJlYiMp8FuY

2018-09-12 19:28 UTC, hja685 commented on examples/ELD/ELD.ino
> +  if(can_Val == CAN_250KBS | can_Val == CAN_500KBS | can_Val == CAN_125KBS | can_Val == CAN_666KBS | can_Val == CAN_1000KBS){
|| is desired, just got lazy. It'll be getting changed to && though

2018-09-12 19:29 UTC, hja685 commented on examples/ELD/ELD.ino
> +  //Insert a can_val check here. We need to make sure that this is in place in the event that memory is corrupted.
Thanks

2018-09-12 19:30 UTC, hja685 commented on examples/J1939/J1939.ino
> +/* EEPROM Memory Map */
EEPROM is the same on both sides. which memory values that are read are the only difference.

2018-09-12 19:30 UTC, hja685 commented on examples/J1939/J1939.ino
> +/* EEPROM Memory Map */
I figured it was easier to do it that way.

2018-09-12 19:31 UTC, hja685 commented on examples/J1939/J1939.ino
> +    if(CAN0.checkReceive()== CAN_MSGAVAIL){ //Checking to see if canBus frames have come onto the bus
I'll look into it. Are you running it through a linter when you look through it? you are noticing new lines and /t and spaces that I am not able to see online

2018-09-12 19:31 UTC, hja685 commented on examples/J1939/J1939.ino
> +  /*** Setup the WDT ***/
I can change that. I think I copy and pasted that out.

2018-09-12 19:32 UTC, hja685 commented on examples/J1939/J1939.ino
> +  if(can_Val == CAN_250KBS | can_Val == CAN_500KBS | can_Val == CAN_125KBS | can_Val == CAN_666KBS | can_Val == CAN_1000KBS){
yes

2018-09-12 19:32 UTC, hja685 commented on examples/J1939/J1939.ino
> +    can_val == CAN_250KBS;
yes

2018-09-12 19:33 UTC, bengardiner-at-irdeto commented on examples/J1939/J1939.ino
> +    if(CAN0.checkReceive()== CAN_MSGAVAIL){ //Checking to see if canBus frames have come onto the bus
yes. the linter is my brain tho

2018-09-12 19:33 UTC, hja685 commented on examples/J1939/J1939.ino
> +  // The following sequence is the only way we could get the clkout divisor to stay at 1
I may do that just to clean it up similar to my setupWDT()

2018-09-12 19:33 UTC, bengardiner-at-irdeto commented on examples/J1939/J1939.ino
> +/* EEPROM Memory Map */
kk

2018-09-12 19:34 UTC, hja685 commented on examples/J1939/J1939.ino
> +    if(CAN0.checkReceive()== CAN_MSGAVAIL){ //Checking to see if canBus frames have come onto the bus
🤣

2018-09-12 19:42 UTC, hja685 commented on examples/J1939/J1939.ino
> +/* EEPROM Memory Map */
any issues with doing it that way?

2018-09-12 19:48 UTC, bengardiner-at-irdeto commented on examples/J1939/J1939.ino
> +/* EEPROM Memory Map */
My understanding is that this 'EEPROM' is, in fact, internal to the AVR. So neither AVR is sharing NV data with the other. 

In this case, there is little impact to sharing the same EEPROM layout.

2018-09-12 19:58 UTC, hja685 commented
I'm not sure what was included in the last commit. it says I merged a branch of a branch.

2018-09-12 19:58 UTC, hja685 commented on examples/J1939/J1939.ino
> +/* EEPROM Memory Map */
Yes EEPROM is internal to the AVR.

2018-09-12 19:59 UTC, hja685 commented
@bengardiner-at-irdeto: Updated based on your concerns. Thank you.

2018-09-12 20:01 UTC, bengardiner-at-irdeto commented
> I'm not sure what was included in the last commit. it says I merged a branch of a branch.

that last line
![image](https://user-images.githubusercontent.com/16688119/45450037-e6ed4000-b6a4-11e8-9366-540c3247959f.png)

Is an indication that you pushed a commit with the description 'Merge branch ...' ; the most likely explanation to my mind is that you did a git pull, which defaults to merge. and merges default to making commits (this part is good). If you're worried about git commit aesthetics then you should remember `git pull --rebase`

2018-09-12 20:03 UTC, hja685 commented
Ah okay, I did do a git pull. Everything looks okay. Thanks for helping!

2018-09-12 20:04 UTC, bengardiner-at-irdeto commented
my pleasure

2018-09-12 20:04 UTC, bengardiner-at-irdeto approved these changes

2018-09-12 20:05 UTC, hja685 commented
Hopefully @jeremydaily can review tonight then merge to master.

2018-09-12 21:26 UTC, jmaag15 approved these changes

2018-09-14 03:21 UTC, jeremy-daily approved these changes
Looks like good progress. We do need to think about a library,

2018-09-14 03:21 UTC, merged