CAN seen on ELD Side
Heavy-Vehicle-Networking-At-U-Tulsa/CAN-Data-Diode pull request #5
Opened 2018-07-03 15:26 UTC by hja685

Need to fix the clock output from ELD MCP25625 to the rest of the board.

2018-07-03 15:33 UTC, bengardiner-at-irdeto requested changes

2018-07-03 15:33 UTC, bengardiner-at-irdeto commented on CAN_test_compile.ino
> +  pinMode(5,
Is this correct? I don't see how this is still compiling w/o erros...

https://github.com/Heavy-Vehicle-Networking-At-U-Tulsa/CAN-Data-Diode/blob/a36eae462624bfeef185bb6a93749a5e66c18657/CAN_test_compile.ino#L126-L128

The `(` there is unterminated

2018-07-03 15:34 UTC, hja685 commented on CAN_test_compile.ino
> +  pinMode(5,
Oops!

2018-07-03 15:38 UTC, hja685 commented
@bengardiner-at-irdeto I fixed that just now I think?

2018-07-03 15:44 UTC, bengardiner-at-irdeto commented on CAN_test_compile.ino
> +  pinMode(5, INPUT);
ok -- this probably compiles now

a minor follow up review comment: you should always `define` you magic numbers so that their intent is clear in-context. e.g. don't put `5` here ; put something like `PIN_MISO` ...

2018-07-03 15:44 UTC, bengardiner-at-irdeto commented
looks like it compiles now. But did you change line endings or something? The diff is all-red and green

https://github.com/Heavy-Vehicle-Networking-At-U-Tulsa/CAN-Data-Diode/pull/5/files/a36eae462624bfeef185bb6a93749a5e66c18657..2571cf47ee27b044e99084819d85ce9eac0679b1

2018-07-03 15:47 UTC, hja685 commented
@bengardiner-at-irdeto I don't know what happened there. all I added was "_, INPUT);_" to the line you commented on. Maybe it is because I changed it here in the editor?

2018-07-03 16:33 UTC, bengardiner-at-irdeto commented
I checked out the file -- it looks like you saved the most recent version with DOS line endings whereas the version that was previously committed had UNIX line endings

2018-07-04 13:14 UTC, bengardiner-at-irdeto commented
I fixed it for you with `dos2unix CAN_test_compile.ino`

2018-07-04 13:19 UTC, merged