Eld err monitor
Heavy-Vehicle-Networking-At-U-Tulsa/CAN-Data-Diode pull request #8
Opened 2018-09-08 01:35 UTC by hja685

This has autobaud and an example of error monitoring using the EFLG flag.

2018-09-08 07:28 UTC, hja685 commented
I have added lower power settings and modified a test sleep_test.ino file. Should work on an 8 second timer.

2018-09-09 10:04 UTC, jeremy-daily commented
Please update the README.md file to explain which sketch is the one to use. Is there any reason to hang onto old files? Git keeps them, so you can find them later. There should only be 2 sketches: one for the J1939 side and one for the ELD side.

2018-09-10 13:13 UTC, bengardiner-at-irdeto commented on docs/index.html
> +</html>
really minor: trailing newline now gone. the only impact is losing the ability to diff the last line reliably. It's usually good hygene to keep the files with trailing new lines

2018-09-10 13:17 UTC, bengardiner-at-irdeto commented on examples/ELD_Side_with_autobaud/ELD_Side_with_autobaud.ino
> +#define CS 6 //The chip select pin for SPI
minor: weird to have a comment on only this pin definition

2018-09-10 13:28 UTC, bengardiner-at-irdeto commented on examples/ELD_Side_with_autobaud/ELD_Side_with_autobaud.ino
> +      if ((data & 0x80) == 0x80) PORTB |= 0b00000001; //Set the bit on PB0
you should define a 'constant' for the value `0b00000001` and then you can do `~X` for the constant `0b11111110` below.

In general, avoid 'magic' numbers like these. create well-name constants or defines.

2018-09-10 14:18 UTC, bengardiner-at-irdeto requested changes
comment 'about' a file (can't comment inline): it's kinda weird to `mcp_can.cpp → src/CANDataDiode.cpp` when the file is copyrighted and licensed under GPL using the name `mcp_can.cpp`. Is the name change necessary? Are you extending that file from it's original?

2018-09-10 14:18 UTC, bengardiner-at-irdeto commented on examples/ELD_Side_with_error_check/ELD_Side_with_error_check.ino
> +bool canTest = 1;
remove this unused var

2018-09-10 14:18 UTC, bengardiner-at-irdeto commented on examples/ELD_Side_with_error_check/ELD_Side_with_error_check.ino
> +uint32_t currentMillis = millis();
it 'works' to intialize a variable with the return of a function call. But this practice can go awry on you in many cases. Best practice is to initialize globals with literals in these contexts. If a function call is needed for an initial value, assign it from teh context of a function somewhere

2018-09-10 14:18 UTC, bengardiner-at-irdeto commented on examples/ELD_Side_with_error_check/ELD_Side_with_error_check.ino
> +  SPI_transfer(0x03); // READ instruction
define `0x03` and `0x1D` and `0x00` below as well-named constants

2018-09-10 14:18 UTC, bengardiner-at-irdeto commented on examples/ELD_Side_with_error_check/ELD_Side_with_error_check.ino
> +    SPI_transfer(0x02); //Write command
make a well-named constant

2018-09-10 14:18 UTC, bengardiner-at-irdeto commented on examples/ELD_Side_with_error_check/ELD_Side_with_error_check.ino
> +  switch (canSpeed)
the values in the switch statements should be well-named constants

2018-09-10 14:18 UTC, bengardiner-at-irdeto commented on examples/ELD_Side_with_error_check/ELD_Side_with_error_check.ino
> +    if(CAN0.checkReceive()==3){ //Checking to see if canBus frames have come onto the bus
is this checking for 3 frames received? or is `3` a magic value?

2018-09-10 14:18 UTC, bengardiner-at-irdeto commented on examples/ELD_Side_with_error_check/ELD_Side_with_error_check.ino
> +void sos(uint8_t led){
cute. morse for sos

2018-09-10 14:18 UTC, bengardiner-at-irdeto commented on examples/ELD_Side_with_error_check/ELD_Side_with_error_check.ino
> +  // set the digital pin as output:
comment is out-of-date wrt code

2018-09-10 14:18 UTC, bengardiner-at-irdeto commented on examples/ELD_Side_with_error_check/ELD_Side_with_error_check.ino
> + // determining the right clkout divisor
comment out of date with code -- the code here isn't 'determining' anything really. i.e. there's no feedback of  anything into a decision by the code.

2018-09-10 14:18 UTC, bengardiner-at-irdeto commented on examples/ELD_Side_with_error_check/ELD_Side_with_error_check.ino
> +  switch (canSpeed)
also, I won't open more comments for this recurring issue: it WBN to have all magic-values as with descriptive names as constants or defines

2018-09-10 14:18 UTC, bengardiner-at-irdeto commented on examples/ELD_Side_with_error_check/ELD_Side_with_error_check.ino
> +  SPI_transfer(0b10000110); //data byte to enable 1 clock out and to enter configuration mode
this comment can't possibly be correct since on line 272 there is a different value getting shifted out in the same sequence of address,mask,value

2018-09-10 14:18 UTC, bengardiner-at-irdeto commented on examples/ELD_Side_with_error_check/ELD_Side_with_error_check.ino
> +  SPI_transfer(0b10000101); //data byte to enable 1 clock out and to enter configuration mode
ditto on comment

2018-09-10 14:18 UTC, bengardiner-at-irdeto commented on examples/ELD_Side_with_error_check/ELD_Side_with_error_check.ino
> +  SPI_transfer(0b10000100); //data byte to enable 1 clock out and to enter configuration mode
ditto on comment

2018-09-10 17:58 UTC, hja685 commented on examples/ELD_Side_with_error_check/ELD_Side_with_error_check.ino
> +    if(CAN0.checkReceive()==3){ //Checking to see if canBus frames have come onto the bus
I'm actually not sure why I put 3 there. I will be reviewing all of these "magic values" and creating well defined constants.

2018-09-10 17:58 UTC, hja685 commented on examples/ELD_Side_with_error_check/ELD_Side_with_error_check.ino
> +void sos(uint8_t led){
lol thank you for calling it cute and not anything worse haha

2018-09-10 18:00 UTC, hja685 commented
Sorry for my horrible variable management. @bengardiner-at-irdeto @sooooo I'll be correcting this.

2018-09-11 03:49 UTC, hja685 commented
@bengardiner-at-irdeto thank you for your comments. I have made the requested changes. Can you please re-review to see if how I handled everything is appropriate.

2018-09-11 12:52 UTC, bengardiner-at-irdeto approved these changes
I suggest you start using a linter on your source to keep it 'cleaner'. e.g. https://github.com/cpplint/cpplint (which works on arduino .ino files too)

2018-09-11 12:52 UTC, bengardiner-at-irdeto commented on examples/ELD_Side_with_error_check_LOW_POWER_WDT/ELD_Side_with_error_check_LOW_POWER_WDT.ino
> +    digitalWrite(CS,LOW);
you switched indents to 2 spaces here.

2018-09-11 12:52 UTC, bengardiner-at-irdeto commented on examples/ELD_Side_with_error_check_LOW_POWER_WDT/ELD_Side_with_error_check_LOW_POWER_WDT.ino
> +    if(CAN0.getError()&& 0b00000001){// Check the first bit of the register
magic value `0b00000000000000000001`

2018-09-11 12:52 UTC, bengardiner-at-irdeto commented on examples/ELD_Side_with_error_check_LOW_POWER_WDT/ELD_Side_with_error_check_LOW_POWER_WDT.ino
> +      EEPROM.write(0x00, autobaudCan_Val);
`0x00` is a magic number: it is the ***address*** of the saved can speed in EEPROM

2018-09-11 19:35 UTC, bengardiner-at-irdeto commented on examples/ELD_Side_with_error_check_LOW_POWER_WDT/ELD_Side_with_error_check_LOW_POWER_WDT.ino
> +  DDRB = ~second_bit; // Setting up inputs and outputs for DDRB.
hmmm. OK this is a bit silly.
The idea of well-named constants is to describe the intent of the bit... if there really is no intention or better name than bit 2; just use ~(1<<1) here

2018-09-11 19:35 UTC, hja685 commented
@bengardiner-at-irdeto I added an EEPROM map to reference specific EEPROM values. I am now going to write another configuration sketch to allow these values to be set for the initial upload. also I added a "register masks" section and just threw all the values in there. That way the end user can build masks as necessary. 

Sound good?

2018-09-11 19:36 UTC, hja685 commented on examples/ELD_Side_with_error_check_LOW_POWER_WDT/ELD_Side_with_error_check_LOW_POWER_WDT.ino
> +  DDRB = ~second_bit; // Setting up inputs and outputs for DDRB.
lol okay was just trying to cover all my bases.

2018-09-11 19:37 UTC, hja685 commented on examples/ELD_Side_with_error_check_LOW_POWER_WDT/ELD_Side_with_error_check_LOW_POWER_WDT.ino
> +  DDRB = ~second_bit; // Setting up inputs and outputs for DDRB.
actually now that I think about it all the other values need to be 1s to describe whether they are inputs of outputs. I'll just go back to 0b11111101...

2018-09-12 00:11 UTC, hja685 commented
@jeremy-daily any reason I can't merge? Waiting for your review.

2018-09-12 01:43 UTC, jeremy-daily commented
Let's merge so we can clean up all the branches and get some testing done!

2018-09-12 01:45 UTC, hja685 commented
What commits did you leave off? @jeremy-daily

2018-09-12 01:45 UTC, merged

2018-09-12 01:48 UTC, hja685 commented
Closed like 30 seconds too soon was actively saving latest updates.

2018-09-12 01:48 UTC, jeremy-daily commented
I accidently closed without merging. It’s fixed now.

 

From: hja685 <notifications@github.com> 
Sent: Tuesday, September 11, 2018 8:45 PM
To: Heavy-Vehicle-Networking-At-U-Tulsa/CAN-Data-Diode <CAN-Data-Diode@noreply.github.com>
Cc: jeremy-daily <jeremy@synercontechnologies.com>; Mention <mention@noreply.github.com>
Subject: Re: [Heavy-Vehicle-Networking-At-U-Tulsa/CAN-Data-Diode] Eld err monitor (#8)

 

What commits did you leave off? @jeremy-daily <https://github.com/jeremy-daily> 

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/Heavy-Vehicle-Networking-At-U-Tulsa/CAN-Data-Diode/pull/8#issuecomment-420483639> , or mute the thread <https://github.com/notifications/unsubscribe-auth/AG1LaG0Z6RuIKeKG__tWUHToVMozfKUAks5uaGcmgaJpZM4Wfqac> .  <https://github.com/notifications/beacon/AG1LaOdptrt0TOOs9rzQvG4omTRav5wGks5uaGcmgaJpZM4Wfqac.gif>

2018-09-12 01:49 UTC, hja685 commented
Let me push this last commit before closing it.

2018-09-12 01:49 UTC, hja685 commented
You came in right as I was about to commit on this branch.

2018-09-12 01:50 UTC, jeremy-daily commented
ok, go ahead and take care of the merge.